runtime: python27
api_version: 1
threadsafe: true
service: default

# [START handlers]
handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: main.app
- url: /assets
  static_dir: assets
  application_readable: true
# [END handlers]

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: your-bucket-name
#[END env]


libraries:
- name: ssl
  version: latest
- name: numpy
  version: latest
- name: matplotlib
  version: 1.2.0